title: Pedagogy of the Oppressed
description: > # this means to ignore newlines until "baseurl:"
  Online Book Club
baseurl: "/PotO/" # the subpath of your site, e.g. /blog
url: "lqb2.co/PotO" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: MIT Community Innovators Lab
  link: "https://www.facebook.com/MITCoLab"

# google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/MITCoLab
  - title: twitter
    url: https://twitter.com/MITCoLab

# Build settings
markdown: kramdown
permalink: pretty